version: '3.9'

services:
  # mongo-express:
    # image: mongo-express:1.0.0-alpha.4
    # restart: always
    # ports:
      # - 8081:8081
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # ME_CONFIG_MONGODB_SERVER: mongodb_db
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb_db:27017/
      
  mongodb_db:
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
