version: '3.9'

services:
  expense-app-backend:
    image: nahwu2/expense-app-backend:0.1
    restart: always
    ports:
      - 8080:8080
      
  mongodb:
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
